---
- hosts: all
  any_errors_fatal: true
  serial: 50%
  order: shuffle
  tasks:
    - include_role:
        name: konstruktoid.hardening
    - include_role:
        name: docker
      when: ansible_distribution == 'Ubuntu'
...
